[workspace]
resolver = "2"
members = [
    "portage-versions",
    "portage-dep",
    "portage-use-reduce",
    "portage-profile",
    "portage-repo",
    "portage-required-use",
    "portage-fetch",
    "versions-harness",
    "atom-harness",
    "use-reduce-harness",
    "required-use-harness",
    "portuale",
]

[workspace.package]
edition = "2021"

[profile.release]
panic = "abort"
